<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "oauth_scopes".
 *
 * @property string $scope
 * @property integer $is_default
 * @property string $aliasModel
 */
abstract class OauthScopes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'oauth_scopes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['scope', 'is_default'], 'required'],
            [['is_default'], 'integer'],
            [['scope'], 'string', 'max' => 2000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'scope' => 'Scope',
            'is_default' => 'Is Default',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\OauthScopesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\OauthScopesQuery(get_called_class());
    }


}
