<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "oauth_users".
 *
 * @property string $username
 * @property string $password
 * @property string $first_name
 * @property string $last_name
 * @property string $aliasModel
 */
abstract class OauthUsers extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'oauth_users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username'], 'required'],
            [['username', 'first_name', 'last_name'], 'string', 'max' => 255],
            [['password'], 'string', 'max' => 2000],
            [['username'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'username' => 'Username',
            'password' => 'Password',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\OauthUsersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\OauthUsersQuery(get_called_class());
    }


}
