<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "oauth_public_keys".
 *
 * @property string $client_id
 * @property string $public_key
 * @property string $private_key
 * @property string $encryption_algorithm
 * @property string $aliasModel
 */
abstract class OauthPublicKeys extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'oauth_public_keys';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id'], 'required'],
            [['client_id'], 'string', 'max' => 255],
            [['public_key', 'private_key'], 'string', 'max' => 2000],
            [['encryption_algorithm'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'client_id' => 'Client ID',
            'public_key' => 'Public Key',
            'private_key' => 'Private Key',
            'encryption_algorithm' => 'Encryption Algorithm',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\OauthPublicKeysQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\OauthPublicKeysQuery(get_called_class());
    }


}
